# Generated by Django 5.0.2 on 2024-03-16 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bloodGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('APositive', models.IntegerField()),
                ('ANegative', models.IntegerField()),
                ('ABPositive', models.IntegerField()),
                ('ABNegative', models.IntegerField()),
                ('OHPositive', models.IntegerField()),
                ('OHNegative', models.IntegerField()),
                ('OPositive', models.IntegerField()),
                ('ONegative', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='bloodReciever',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('contact_no', models.IntegerField()),
                ('reciever', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
